DECLARE @EXPENSES TABLE (ID INT, EXPENSEDAY INT, REASON VARCHAR(100), AMOUNT DECIMAL(12,2))
INSERT INTO @EXPENSES (ID, EXPENSEDAY, REASON, AMOUNT)
VALUES
(1, 1, 'Groceries', 10),
(2, 1, 'Restaurants', 20),
(3, 1, 'Gym', 10),
(4, 2, 'Groceries', 20),
(5, 2, 'Travel', 15),
(6, 2, 'Drinks', 8),
(7, 3, 'Restaurants', 40),
(8, 3, 'Travel', 30)

SELECT EXPENSEDAY, REASON, AMOUNT, 
	SUM(AMOUNT) OVER(ORDER BY ID) AS RUNNING_TOTAL, 
	SUM(AMOUNT) OVER(PARTITION BY EXPENSEDAY ORDER BY ID) AS DAY_RUNNING_TOTAL
FROM @EXPENSES
