DECLARE @EXPENSES TABLE (ID INT IDENTITY(1,1), EXPENSEDAY INT, REASON VARCHAR(100), AMOUNT DECIMAL(12,2))
INSERT INTO @EXPENSES (ID, EXPENSEDAY, REASON, AMOUNT)
VALUES
(1, 'Groceries', 10),
(1, 'Restaurants', 20),
(1, 'Gym', 10),
(2, 'Groceries', 20),
(2, 'Travel', 15),
(2, 'Drinks', 8),
(3, 'Restaurants', 40),
(3, 'Travel', 30)

SELECT *, 
	ROW_NUMBER() OVER(ORDER BY EXPENSEDAY) AS [ROW_NUMBER],
	RANK() OVER(ORDER BY EXPENSEDAY) AS [RANK],
	DENSE_RANK() OVER(ORDER BY EXPENSEDAY) AS [DENSE_RANK]
FROM @EXPENSES